VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsTopperOrPoor"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'**Abdul***
Public strdeptSel As String
Public flgDeptSel As Boolean
Public intDaysEnter As Integer
Public firstMthHeader As String
Public secondMthHeader As String
Public rptheader As String
Public staus As String

Public strdeptSel1 As String
Public flgDeptSel1 As Boolean
Public intDaysEnter1 As Integer
Public firstMthHeader1 As String
Public secondMthHeader1 As String
Public rptheader1 As String
Public staus1 As String

Public strdeptSel2 As String
Public flgDeptSel2 As Boolean
Public intDaysEnter2 As Integer
Public firstMthHeader2 As String
Public secondMthHeader2 As String
Public rptheader2 As String
Public staus2 As String


Public strdeptSel3 As String
Public flgDeptSel3 As Boolean
Public intDaysEnter3 As Integer
Public firstMthHeader3 As String
Public secondMthHeader3 As String
Public rptheader3 As String
Public staus3 As String

Public strdeptSel4 As String
Public flgDeptSel4 As Boolean
Public intDaysEnter4 As Integer
Public firstMthHeader4 As String
Public secondMthHeader4 As String
Public rptheader4 As String
Public staus4 As String

Public strdeptSel5 As String
Public flgDeptSel5 As Boolean
Public intDaysEnter5 As Integer
Public firstMthHeader5 As String
Public secondMthHeader5 As String
Public rptheader5 As String
Public staus5 As String
'**Abdul***

